<a href="https://colab.research.google.com/github/cjaucian/MAT421/blob/main/ModuleD_1_1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.1 Introduction**

Linear algebra concepts play an important role in data science and machine learning algorithms. Basic concepts like vector spaces, orthogonality, eigenvalues, and matrix decomposition make up the process for solving problems in data science.

# **1.2 Elements of Linear Algebra**

**Linear Spaces**

A new vector which is created by taking an initial subset and multiplying a constant then adding the results is called a linear combination. A result of the linear comination is a linear subspace.

Definition: A linear subspace, V, is a subset of U that remains true under vector addition and scalar multiplication. For example, if u1 and u2 are included in set U. Additionally, alpha is included in the real number set. Then it must be true that:
u1 + u2 are included in set U, and a*u1 is included in set U. Thus, the sum of a*un is defined as a linear combination.

Sets can be defined as linearly independent or linearly dependent depending on whether the objects in the set can be shown as a linear combination of the other objects within the same set. If no other linear combinations are created, then the set is consided linearly independent. If this is not true, the set is linearly dependent.

**Example**  Given the row vectors v = [1, 2, 3], w = [2, 2, 5], and u = [0, -3, 0], write the vector x = [-4, -8, -9].

In [5]:
import numpy as np

A = np.array([[1, 2, 3], [2, 2, 5], [0, -3, 0]])
y = np.array([0, 0, 0])
x = np.linalg.solve(A, y)
print(x)

[ 0. -0.  0.]


By taking the row vectors and setting them equal to the zero vector, we can determine if they are linearly independent. Since we received a vector of [0, 0, 0], we can determine that they are linearly independent.

**Orthogonality**

Orthonormal vectors are a set of vectors that sum to the zero vector and also has a set with a magnitude of 1.

An optimized combination is not always possible, so the Best Approximation Theorem finds a solution that optimizes the combination of variables that gets closest to orthonormal basis.

**Eigenvalues and Eigenvectors**

A linear transformation of x, which is Ax will have a special transform:
A * x = lambda * x

In this case, A is a square matrix of dimensions n x n and x is a column vector of n x 1. For any lambda that satisfies the special transform equation above, is called an eigenvalue of A. The vector, x, is called the eigenvector that relates to the eigenvalue, lambda.

**Example** Use numpy.linalg in Python to find the eigenvalue and eigenvector for given matrix and vector.

Calculate the eigenvalues and eigenvectors for maxtrix A = [0,2],[2,3].

In [10]:
import numpy as np
from numpy.linalg import eig

A = np.array([[0,2],
              [2,3]])

w,v = eig(A)

print("Eigenvalue: ", w)
print("Eigenvector", v)

Eigenvalue:  [-1.  4.]
Eigenvector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


Compute the eigenvalues and eigenvectors for matrix A = [1 1 4], [1 4 5], [1 2 3].

In [11]:
A = np.array([[1,1,4],
              [1,4,5],
              [1,2,3]])

w,v = eig(A)
print("Eigenvalue: ", w)
print("Eigenvector: ", v)

Eigenvalue:  [ 7.38502039 -0.49012347  1.10510308]
Eigenvector:  [[ 0.40856011  0.88957079  0.81314813]
 [ 0.79166661  0.23684039 -0.55929255]
 [ 0.4542495  -0.39060267  0.16118923]]


# **1.3 Linear Regression**

A simple way to model practical applications is linear regression. This is an approximation between unknown parameters which has been modeled by a simple linear equation.

QR Decomposition is a method for solving least squares regression models. We take a matrix A and decompose it into two matrices Q and R. Q is an orthogonal matrix and R is special matrix called an upper triangular matrix. An upper triangular matrix has a diagonal boundary in which the values below the boundary are all zeros. The diagonal boundary are the the eigenvalues of the matrix.

**Example** Use the qr function in numply.linalg to decompose matrix A = [0,4],[5,6]. Then verify the results.

In [13]:
import numpy as np
from numpy.linalg import qr

A = np.array([[0, 4],[5, 6]])

q,r = qr(A)

print("Q: ", q)
print("R: ", r)

b = np.dot(q, r)
print("QR: ", b)

Q:  [[ 0. -1.]
 [-1.  0.]]
R:  [[-5. -6.]
 [ 0. -4.]]
QR:  [[0. 4.]
 [5. 6.]]


In problems where we are trying to solve the system Ax = b, we can use the Least-squares Problem since the solution is often inconsistent. In this system, A is a n x m matrix and be is a n x 1 vector. By using an approximation of Ax, we can approximate b. If the matrix A is a square matrix, meaning that n = m then we can simply use the matrix inverse to find the solution. But we use the Lease-squares Problem assuming that n > m. Since n > m, is not a square matrix we cannot use the inverse matrix method.